version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - "./frontend:/app/frontend"
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
