version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    volumes:
      - "./frontend:/app/frontend"
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: locationSearchApp
      POSTGRES_USER: vua36
      POSTGRES_PASSWORD: hl1999
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data  # Persist data across restarts

volumes:
  postgres_data:

